airline/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('flights/', include('flights.urls')),
    path("users/", include("users.urls")),
]

flights/urls.py
from django.urls import path
from . import views

app_name = 'flights'
urlpatterns = [
    path("", views.index, name='index'),
    path("<int:flight_id>", views.flight, name='flight'),
    path("<int:flight_id>/book", views.book, name='book'),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name='index'),
    path("login", views.login_view, name='login'),
    path("logout", views.logout_view, name='logout'),
]

flights/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.fields import DurationField

# Create your models here.
class Airport(models.Model):
    code = models.CharField(max_length=3)
    city = models.CharField(max_length=64)

    def __str__(self) -> str:
        return f"{self.city} ({self.code})"

class Flight(models.Model):
    origin = models.ForeignKey(Airport,on_delete=models.CASCADE, related_name='departures')
    destination = models.ForeignKey(Airport, on_delete=CASCADE, related_name='arrivals')
    duration = models.IntegerField()

    def __str__(self) -> str:
        return f"Flight ID: {self.id} from {self.origin} to {self.destination} in {self.duration} minutes"
    
    def is_valid_flight(self):
        return self.origin != self.destination and self.duration >= 0

class Passenger(models.Model):
    first = models.CharField(max_length=100)
    last = models.CharField(max_length=100)
    flights = models.ManyToManyField(Flight, blank=True, related_name='yolcular')

    def __str__(self) -> str:
        return f"{self.first} {self.last}"

users/models.py
from django.db import models

# Create your models here.

flights/views.py
from django.shortcuts import render
from .models import *
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
def index(request):
    return render(request, "flights/index.html", {
        "flights": Flight.objects.all()
    })

def flight(request, flight_id):
    flight = Flight.objects.get(pk=flight_id)
    return render(request, "flights/flight.html", {
        "flight":flight,
        "passengers": flight.yolcular.all(),
        "non_passengers": Passenger.objects.exclude(flights=flight).all()
    })

def book(request, flight_id):
    if request.method == "POST":
        flight = Flight.objects.get(pk=flight_id)
        passenger = Passenger.objects.get(pk=int(request.POST["passenger"]))
        passenger.flights.add(flight)
        return HttpResponseRedirect(reverse("flights:flight", args=(flight.id,)))

users/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls.base import reverse
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    return render(request, "users/user.html")

def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "users/login.html", {
                "message": "Invalid credentials"
            })
    return render(request, "users/login.html")

def logout_view(request):
    logout(request)
    return render(request, "users/login.html", {
        "message": "Logged out"
    })

flights/templates/flights/flight.html
{% extends 'flights/layout.html' %}

{% block title %}
<title> Flight number {{ flight.id }} </title>
{% endblock%}

{% block body %}
<h1> FLIGHT {{ flight.id }} </h1>

<ul>

        <li> Origin: {{ flight.origin }} </li>
        <li> Destination: {{ flight.destination }} </li>
        <li> Duration: {{ flight.duration }}</li>

</ul>

<h3> Passengers </h3>
    <ul>
        {% for passenger in passengers %}
            <li> {{ passenger }}</li>
        {% empty %}
            <li> No passenger </li>
        {% endfor %}
    </ul>

    <h2> Add passenger </h2>
    <form action="{% url 'flights:book' flight.id %}" method="post">
        {% csrf_token %}
        <select name="passenger" id="">
            {% for passenger in non_passengers %}
                <option value="{{ passenger.id }}"> {{ passenger }} </option>
            {% endfor %}
        </select>
        <input type="submit" value="Add passenger">
    </form>

    <a href="{% url 'flights:index' %}"> Back to the flight lists</a>
{% endblock%}

flights/templates/flights/index.html
{% extends 'flights/layout.html' %}

{% block title %}
<title> Flights list </title>
{% endblock%}

{% block body %}
<h1> FLIGHTS </h1>

<ul>
    {% for ucus in flights%}
    <li> 
        <a href="{% url 'flights:flight' ucus.id %}">
           Flight nr. {{ ucus.id }} aus {{ ucus.origin }} nach {{ ucus.destination }}
    <!-- alternatively ----- Flight {{ flight.id}} {{ flight.origin}} {{ flight.destination }} gibi de 
    yazabilirdin  -->
        </a>
    </li>
    {% endfor %}
</ul>


{% endblock%}

flights/templates/flights/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>Document</title>
    {% endblock %}
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

users/templates/users/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Users </title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

users/templates/users/login.html
{% extends "users/layout.html" %}

{% block body %}

    {% if message %}
        <div> {{ message }} </div>
    {% endif %}
    
    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <input type="text" name="username" id="" placeholder="Username">
        <input type="password" name="password" id="" placeholder="Password">
        <input type="submit" value="Login">
    </form>

{% endblock %}

users/templates/users/user.html
{% extends "users/layout.html" %}

{% block body %}

    <h1> Welcome {{ request.user.first_name }} </h1>

    <ul>
        <li> Username: {{ request.user.username }} </li>
        <li> Email: {{ request.user.email }} </li>
    </ul>

    <a href="{% url 'logout' %}">Log out</a>
    <br>
    <a href="{% url 'flights:index' %}"> View the flight list </a>
{% endblock %}